id: I2FCD4B1D
initial_creation_type: ebook
source_metadata:
  id: PUN-TG-004
  title: དཀོན་མཆོག་གསུམ་གྱི་རྣམ་པར་ཐར་པ་རྗེས་སུ་དྲན་ཅིང་བྱང་ཆུབ་སྤྱོད་པའི་གཞུང་འགྲེལ་གསལ་བའི་མེ་ལོང་དང་བྱང་ཆུབ་ཕྱོགས་མཐུན་ཆོས་སུམ་ཅུ་རྩ་
  author: མཛད་པ་པོ། ཚངས་དབྱངས་རྒྱ་མཚོ།
  authors: &id001
  - མཛད་པ་པོ། ཚངས་དབྱངས་རྒྱ་མཚོ།
  sku: PUN-TG-004
  cover: TSG-004.jpg
  volume: {}
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: དཀོན་མཆོག་གསུམ་གྱི་རྣམ་པར་ཐར་པ་རྗེས་སུ་དྲན་ཅིང་བྱང་ཆུབ་སྤྱོད་པའི་གཞུང་འགྲེལ་གསལ་བའི་མེ་ལོང་དང་བྱང་ཆུབ་ཕྱོགས་མཐུན་ཆོས་སུམ་ཅུ་རྩ་
  authors: *id001
  sku: PUN-TG-004
  cover: TSG-004.jpg
layers:
- Author
- BookTitle
- Citation
- Commentary
- Sabche
- Tsawa
